// ES6 module syntax
import LocalizedStrings from "react-localization";

export const strAuth = new LocalizedStrings({
  en: {
    signIn: "Sign in",
    signUp: "Sign up",
    email: "email address",
    password: "password",
    autoLogin: "Remember me",
    forgotPassword: "FORGOT YOUR PASSWORD?",
    snsLogin: "or sign in with",
    snsSignUp: "or sign up with",
    changeToSignUp: "CREATE A NEW ACCOUNT",
    changeToSignIn: "I ALREADY HAVE AN ACCOUNT!",
    agreeFirst: "I have read and agree to the ",
    termsOfUse: "Terms of Use",
    agreeSecond: "and",
    customerPolicy: "Customer Privacy Policy.",
    tooLong: "Too long!",
    tooShort: "Too hort!",
    required: "Required",
    Submitting: "Submitting...",
    Loading: "Loading...",
    firstName: "First name",
    lastName: "Last name",
    createNewAccount: "Create a new account",
    welcomeBack: "Welcome Back!",
    mustAgree: "You must accept the terms and conditions",
    invalidEmail: "Please enter a valid email address",
    invalidPassword: "Please enter a valid email address",
    emailConfirm: "Confirm email",
    emailConfirmSub: "A 6-digit code has been sent to",
    emailConfirmSubSecond:
      ". The code will expire in a few minutes, so please hurry up and enter it.",
    checkSpam:
      "Please check your spam box if you haven't receive our email yet.",
    open: " open",
    // : "",
    // : "",
    // : "",
    // : "",
    // : "",
    // : "",
  },
  ko: {
    signIn: "로그인",
    signUp: "회원가입",
    email: "이메일",
    password: "비밀번호",
    autoLogin: "자동로그인",
    forgotPassword: "비밀번호 재발급",
    snsLogin: "또는 SNS 로그인",
    snsSignUp: "또는 SNS 회원가입",
    changeToSignUp: "계정이 아직 없으신가요?",
    changeToSignIn: "이미 계정이 있으신가요?",
    agreeFirst: "'가입하기' 버튼을 누르시면 ",
    termsOfUse: "서비스 이용약관",
    agreeSecond: "및",
    customerPolicy: "개인정보 수집 및 이용 동의 약관",
    agreeThird: "에 동의한 것으로 간주합니다.",
    tooLong: "비밀번호는 12자 이내여야 합니다.",
    tooShort: "비밀번호는 5자 이상이어야 합니다.",
    required: "필수항목입니다.",
    Submitting: "제출 중",
    Loading: "로딩 중입니다...",
    firstName: "이름",
    lastName: "성",
    createNewAccount: "계정생성하기",
    welcomeBack: "반갑습니다!",
    mustAgree: "약관에 동의하셔야 회원가입을 진행할 수 있습니다.",
    invalidEmail: "유효한 이메일 주소를 입력하세요",
    emailConfirm: "코드는 이메일에서 확인하세요",
    emailConfirmSub:
      "에 6자리 코드를 전송했습니다. 코드는 잠시 후에 만료되니 서둘러 입력해주세요.",
    checkSpam: "고객님의 코드를 찾을 수 없나요? 스팸 폴더를 확인해 보세요!",
    open: " 열기",
    // : "",
    // : "",
    // : "",
    // : "",
    // : "",
    // : "",
  },
});
